import bcrypt from "bcryptjs";
export const data = {
  users:[
    {
      name : "Kavya",
      email : "kavya@ebazaar.com",
      password : bcrypt.hashSync('kavs123'),
      isAdmin : true
    },
    {
      name : "Krithika",
      email : "krithika@example.com",
      password : bcrypt.hashSync('krits123'),
      isAdmin : false
    },
  ],
  products: [
    {
      // _id : "1",
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 700,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numOfReviews: 10,
      description: "high quality product",
    },
    {   
        // _id : "2",
        name: "Adidas fit shirt",
        slug: "adidas-fit-shirt",
        category: "shirts",
        image: "/images/p2.jpg",
        price: 650,
        countInStock: 20,
        brand: "Adidas",
        rating: 4.0,
        numOfReviews: 14,
        description: "high quality product",
      },
      {
        // _id : "3",
        name: "Nike slim pant",
        slug: "nike-fit-pant",
        category: "pants",
        image: "/images/p3.jpg",
        price: 750,
        countInStock: 15,
        brand: "Nike",
        rating: 4.5,
        numOfReviews: 15,
        description: "high quality product",
      },
      {
        // _id : "4",
        name: "Adidas fit pant",
        slug: "adidas-fit-pant",
        category: "pants",
        image: "/images/p4.jpg",
        price: 800,
        countInStock: 18,
        brand: "Adidas",
        rating: 4.5,
        numOfReviews: 20,
        description: "high quality product",
      },
  ],
};
